### ISSUE TITLE
specify that numbers of rejected reads are  numbers of rejected reads...

### ISSUE THREAD

**Issue by yannickwurm** [johnomics/RADtools#1]
Hi John,

hope all is well for you.

I'm testdriving your approach. Initially I was using mapping-based approaches, but it turns out that the "non-reference-genome" allele is often missed. Thus an approach such as yours (followed by subsequent mapping to reference genome) may be more defendable. 

Quick useability comment: When running radpools -v, you may want to specify that numbers on the right are rejected reads. Its unclear from the standard output:
OK:  6743812 | FASTQ:        0 | RAD:        0 | Res:   422995 | MID:    33192 | Short:        0

cheers & all the best,
yannick

**Comment by johnomics** [comment]
Fixed in version 1.2.1; added total number of rejected reads to output
