### ISSUE TITLE
minor documentation comments

### ISSUE THREAD

**Issue by yannickwurm** [johnomics/RADtools#2]
In the Manual "5.2  Basic options" doesn't mention -e --expected_tags in the definition list...

**Comment by yannickwurm** [comment]
Ok another one :)  
In manual section 8.3 RADmarkers, you use the term "ClusterAlleles - the number of alleles in this cluster" .... but just a few lines up you say that you'll use the word "Tags"...

**Comment by yannickwurm** [comment]
RADtags script: "-v" is not documented in the command-line --help or in the manual         But is very useful!
(I think I would switch make '-v' the default...

**Comment by yannickwurm** [comment]
RADmarkers requires a .pools file. The error message doesn't make it clear that it needs to be at ../nameofdir.pools

**Comment by johnomics** [comment]
All fixed in 1.2.1
