### ISSUE TITLE
Suggestion: accelerate RADtags script by starting with largest files

### ISSUE THREAD

**Issue by yannickwurm** [johnomics/RADtools#3]
Minor suggestion. 
One of my .reads files is a synthetic parent obtained by concatenating (and sorting) the sequence from ten individuals. 
This file is thus 10 times larger than the others. 
During the embarrassingly parallel parts of the RADtags script, it could be defendable to sort .read files according to size and start with the largest. It's a bit dumb if the largest file is launched last...

cheers,
yannick

**Comment by johnomics** [comment]
Implemented in version 1.2.1
